# Generated by Django 3.2.7 on 2021-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
