# Generated by Django 3.2.7 on 2021-09-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0005_alter_attend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='Status',
            field=models.BooleanField(null=True),
        ),
    ]
